services:
    laravel.hospital:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        container_name: laravel_hospital
        restart: unless-stopped
        working_dir: /var/www/html
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-9005}:80'
            - '${VITE_PORT:-5175}:${VITE_PORT:-5175}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - hospital
        depends_on:
            - mysql
    # Service Nginx
    nginx:
        image: nginx:alpine
        container_name: nginx_hospital
        restart: unless-stopped
        ports:
            - "${APP_FORWARDED_PORT:-8060}:80"
        depends_on:
            - laravel.hospital
        volumes:
            - '.:/var/www/html'
            - ./docker/nginx/laravel_eleven.conf:/etc/nginx/conf.d/laravel_eleven.conf
        networks:
            - hospital
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql_hospital
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3303}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password    #'${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: hospital        #'${DB_DATABASE}'
            MYSQL_USER: hospital                   #'${DB_USERNAME}'
            MYSQL_PASSWORD: password                   #'${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - hospital
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    # Service phpMyAdmin
    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        container_name: phpmyadmin_hospital
        restart: unless-stopped
        ports:
            - "8387:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql
        networks:
            - hospital
    # Service Redis
    redis:
        image: redis:7.2-alpine
        container_name: redis_hospital
        ports:
            - "${REDIS_FORWARDED_PORT:-6359}:6379"
        networks:
            - hospital

networks:
    hospital:
        driver: bridge
volumes:
    sail-mysql:
        driver: local